version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: riskmanager
   # volumes:
   #   - postgres-data:/var/lib/postgresql/data

  flask:
    build: ./server
    restart: always
    #environment:
    #  DATABASE_URL: postgresql://postgres:example@postgres/mydatabase
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  node:
    build: ./client
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - flask

  react:
    build: ./client
    command: ["npm", "start"]
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - flask